name: outdated
on:
  schedule:
    - cron:  '0 5 * * 2' # Once a week, Tues at 5:00PM UTC (9PM PST Mon)
env:
  CI: true
jobs:
  outdated:
    name: "Checking for outdated dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn install
      - name: YOD
        run: yarn outdated
